server:
  port: 8888
  connection-timeout: 60000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #    password:
    password: 123456
    url: jdbc:mysql://localhost:3306/kaoqinsystem?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
  thymeleaf:
    cache: false #关闭缓存
    check-template: false
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  auto:
    openurl: false
  web:
    loginurl: http://localhost:8888
#    googleexcute: C:\Program Files\Google\Chrome\Application\chrome.exe


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: java.resou

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

authority:
  info: '[{
         	"models": [{
         		"modelId": 1,
         		"operation": [1, 2, 3, 4]
         	}, {
         		"modelId": 1000001,
         		"operation": [1, 2, 3, 4]
         	}, {
         		"modelId": 2,
         		"operation": [1, 2, 3, 4]
         	}, {
         		"modelId": 3,
         		"operation": [1, 2, 3, 4]
         	}, {
                "modelId": 7,
                "operation": [1, 2, 3, 4]
         	},{
         		"modelId": 10,
         		"operation": [1, 2, 3, 4]
         	}, {
         		"modelId": 11,
         		"operation": [1, 2, 3, 4]
         	}, {
         		"modelId": 12,
         		"operation": [1, 2, 3, 4]
         	}, {
         		"modelId": 13,
         		"operation": [1, 2, 3, 4]
         	}, {
         		"modelId": 14,
         		"operation": [1, 2, 3, 4]
         	}],
         	"level": 1,
         	"modelId": 1,
         	"name": "管理员"
         }, {
         	"models": [{
         		"modelId": 11,
         		"operation": [4]
         	}, {
         		"modelId": 12,
         		"operation": [4, 1, 2, 3]
         	}, {
         		"modelId": 13,
         		"operation": [4, 1, 2, 3]
         	}, {
         		"modelId": 14,
         		"operation": [4, 1, 2, 3]
         	}],
         	"level": 2,
         	"modelId": 2,
         	"name": "员工"
         }]
'

logging:
  file: log/my.log
  level:
    com.example: DEBUG


